[buildPlans.iosevka-custom]
family = "Iosevka RLTB"
serifs = "sans"
spacing = "fixed"
export-glyph-names = true
# no-ligation = true

[buildPlans.iosevka-custom.ligations]
enables = ["kern-dotty"]

[buildPlans.iosevka-custom.variants.design]
capital-b = "standard-serifless"
capital-d = "more-rounded-serifless"
capital-g = "toothed-serifless-hooked"
capital-i = "serifed"
capital-j = "serifed"
capital-k = "straight-serifless"
capital-l = "serifless"
capital-m = "hanging"
capital-q = "crossing"
capital-s = "serifless"
capital-r = "curly"
capital-y = "straight-serifless"
turn-v = "straight"
a = "double-storey-tailed"
b = "toothed"
d = "toothed-serifless"
f = "flat-hook"
g = "double-storey"
h = "straight"
i = "hooky"
j = "serifed"
k = "straight-serifless"
l = "serifed-flat-tailed"
m = "normal"
n = "straight"
p = "eared"
q = "straight"
r = "serifless"
t = "flat-hook"
u = "toothed"
v = "straight"
w = "straight"
x = "straight-serifless"
y = "straight-turn"
z = "straight-serifless"
zero = "unslashed-oval"
one = "base"
two = "curly-neck"
three = "two-arcs"
four = "semi-open"
five = "oblique-upper-left-bar"
six = "open-contour"
seven = "curly-serifless"
eight = "crossing-asymmetric"
nine = "open-contour"
punctuation-dot = "round"
asterisk = "penta-high"
underscore = "high"
caret = "high"
paren = "normal"
brace = "straight"
number-sign = "slanted"
at = "short"
dollar = "through"
percent = "rings-continuous-slash"
ascii-grave = "straight"
lig-ltgteq = "flat"
eszet = "sulzbacher-descending"
capital-gamma = "top-right-serifed"
lower-lambda = "straight-turn"
tilde = "low"
paragraph-sign = "high"
ampersand = "closed"
ascii-single-quote = "straight"
bar = "natural-slope"