[buildPlans.iosevka-rltb-mono]
	buildTextureFeature = true
	family = "Iosevka RLTB"
	serifs = "sans"
	spacing = "term"
	webfont-formats = ["ttf"]

	[buildPlans.iosevka-rltb-mono.ligations]
		enables = ["kern-dotty", "kern-bars", "center-ops", "slash-asterisk"]

	# including these two prevents oblique from being built
	[buildPlans.iosevka-rltb-mono.slopes.upright]
		angle = 0
		css = "normal"
		menu = "upright"
		shape = "upright"

	[buildPlans.iosevka-rltb-mono.slopes.italic]
		# 9.4 comes straight from [Iosevka Customizer](https://typeof.net/Iosevka/customizer)
		angle = 9.4
		css = "italic"
		menu = "italic"
		shape = "italic"

	[buildPlans.iosevka-rltb-mono.variants.design]
		# Capital letters
		capital-a = "straight-serifless"
		capital-b = "standard-serifless"
		capital-c = "serifless"
		capital-d = "more-rounded-serifless"
		capital-e = "serifless"
		capital-f = "serifless"
		capital-g = "toothed-serifless-hooked"
		capital-h = "serifless"
		capital-i = "serifed"
		capital-j = "serifed"
		capital-k = "straight-serifless"
		capital-l = "serifless"
		capital-m = "hanging-serifless"
		capital-n = "standard-serifless"
		capital-p = "closed-serifless"
		capital-q = "crossing-baseline"
		capital-r = "straight-serifless"
		capital-s = "serifless"
		capital-t = "serifless"
		capital-u = "toothless-rounded-serifless"
		capital-v = "straight-serifless"
		capital-w = "straight-serifless"
		capital-x = "straight-serifless"
		capital-y = "straight-serifless"
		capital-z = "straight-serifless"

		# Lowercase letters
		a = "double-storey-serifless"
		b = "toothed-serifless"
		c = "serifless"
		d = "toothed-serifless"
		e = "flat-crossbar"
		f = "flat-hook-serifless-crossbar-at-x-height"
		g = "single-storey-serifless"
		h = "straight-serifless"
		i = "hooky"
		j = "serifed"
		k = "straight-serifless"
		l = "serifed-flat-tailed"
		m = "serifless"
		n = "straight-serifless"
		p = "eared-serifless"
		q = "straight-serifless"
		r = "hookless-serifless"
		s = "serifless"
		t = "flat-hook-short-neck"
		u = "toothed-serifless"
		v = "straight-serifless"
		w = "straight-serifless"
		x = "straight-serifless"
		y = "straight-turn-serifless"
		z = "straight-serifless"

		# Digits (comments prevent sorting of lines alphabetically)
		# 0
		zero = "oval-tall-slashed"
		# 1
		one = "base"
		# 2
		two = "curly-neck-serifless"
		# 3
		three = "two-arcs"
		# 4
		four = "semi-open-serifless"
		# 5
		five = "oblique-arched-serifless"
		# 6
		six = "open-contour"
		# 7
		seven = "bend-serifless"
		# 8
		eight = "crossing-asymmetric"
		# 9
		nine = "open-contour"

		# Puncutation
		ampersand = "closed"
		ascii-grave = "straight"
		ascii-single-quote = "straight"
		asterisk = "penta-high"
		at = "compact"
		bar = "natural-slope"
		brace = "curly"
		braille-dot = "round"
		caret = "medium"
		cent = "through"
		decorative-angle-brackets = "middle"
		diacritic-dot = "round"
		dollar = "through"
		guillemet = "curly"
		micro-sign = "tailed-serifless"
		number-sign = "slanted"
		paren = "normal"
		percent = "rings-continuous-slash"
		pilcrow = "high"
		punctuation-dot = "round"
		question = "smooth"
		tilde = "low"
		tittle = "round"
		underscore = "high"

		# ligatures
		lig-double-arrow-bar = "with-notch"
		lig-equal-chain = "with-notch"
		lig-hyphen-chain = "with-notch"
		lig-ltgteq = "flat"
		lig-neq = "slightly-slanted-dotted"
		lig-plus-chain = "with-notch"
		lig-single-arrow-bar = "with-notch"

		# Other alphabets
		capital-delta = "straight"
		capital-eszet = "rounded-serifed"
		capital-gamma = "top-right-serifed"
		capital-lambda = "straight-top-serifed"
		capital-thorn = "serifless"
		eszet = "traditional-bottom-serifed"
		long-s = "flat-hook-diagonal-tailed-middle-serifed"
		lower-alpha = "crossing"
		lower-beta = "standard"
		lower-chi = "semi-chancery-curly-serifless"
		lower-delta = "rounded"
		lower-eta = "serifless"
		lower-eth = "curly-bar"
		lower-gamma = "casual"
		lower-iota = "tailed-serifed"
		lower-kappa = "curly-serifless"
		lower-lambda = "tailed-turn"
		lower-mu = "tailed-serifless"
		lower-nu = "casual"
		lower-phi = "cursive"
		lower-pi = "tailed"
		lower-psi = "serifless"
		lower-tau = "semi-tailed"
		lower-theta = "oval"
		lower-thorn = "serifless"
		lower-upsilon = "casual-serifed"
		lower-xi = "flat-top"
		partial-derivative = "curly-bar"


	[buildPlans.iosevka-rltb-mono.variants.italic]
		# lowercase overrides
		a = "single-storey-tailed"
		d = "tailed-serifless"
		e = "rounded"
		f = "flat-hook-tailed"
		g = "single-storey-flat-hook-serifless"
		h = "tailed-serifless"
		i = "serifed-flat-tailed"
		k = "straight-serifless"
		l = "flat-tailed"
		m = "tailed-serifless"
		n = "tailed-serifless"
		q = "tailed-serifless"
		u = "tailed-serifless"

[buildPlans.iosevka-rltb-sans]
	buildTextureFeature = true
	export-glyph-names = false
	family = "Iosevka RLTB Sans"
	serifs = "sans"
	spacing = "quasi-proportional"
	webfont-formats = ["ttf"]

	[buildPlans.iosevka-rltb-sans.slopes.upright]
		angle = 0
		css = "normal"
		menu = "upright"
		shape = "upright"

	[buildPlans.iosevka-rltb-sans.slopes.italic]
		angle = 9.4
		css = "italic"
		menu = "italic"
		shape = "italic"


	[buildPlans.iosevka-rltb-sans.variants.design]
		# Capital letters
		capital-a = "straight-serifless"
		capital-b = "standard-serifless"
		capital-c = "serifless"
		capital-d = "more-rounded-serifless"
		capital-e = "serifless"
		capital-f = "serifless"
		capital-g = "toothed-serifless-hooked"
		capital-h = "serifless"
		capital-i = "serifed"
		capital-j = "serifed"
		capital-k = "straight-serifless"
		capital-l = "serifless"
		capital-m = "hanging-serifless"
		capital-n = "standard-serifless"
		capital-p = "closed-serifless"
		capital-q = "crossing"
		capital-r = "straight-serifless"
		capital-s = "serifless"
		capital-t = "serifless"
		capital-u = "toothless-rounded-serifless"
		capital-v = "straight-serifless"
		capital-w = "straight-serifless"
		capital-x = "straight-serifless"
		capital-y = "straight-serifless"
		capital-z = "straight-serifless"

		# Lowercase letters
		a = "double-storey-serifless"
		b = "toothed-serifless"
		c = "serifless"
		d = "toothed-serifless"
		e = "flat-crossbar"
		f = "flat-hook-serifless-crossbar-at-x-height"
		g = "double-storey"
		h = "straight-serifless"
		i = "serifless"
		j = "flat-hook-serifless"
		k = "straight-serifless"
		l = "flat-tailed"
		m = "serifless"
		n = "straight-serifless"
		p = "eared-serifless"
		q = "straight-serifless"
		r = "compact-serifless"
		s = "serifless"
		t = "flat-hook-short-neck"
		u = "toothed-serifless"
		v = "straight-serifless"
		w = "straight-serifless"
		x = "straight-serifless"
		y = "straight-turn-serifless"
		z = "straight-serifless"

		# Digits
		eight = "crossing-asymmetric"
		five = "oblique-upper-left-bar"
		four = "semi-open"
		nine = "open-contour"
		one = "base"
		seven = "bend-serifless"
		six = "open-contour"
		three = "two-arcs"
		two = "curly-neck"
		zero = "oval-unslashed"

		# Puncutation
		ampersand = "closed"
		ascii-grave = "straight"
		ascii-single-quote = "straight"
		asterisk = "penta-high"
		at = "compact"
		bar = "natural-slope"
		brace = "straight"
		caret = "medium"
		cent = "through"
		diacritic-dot = "round"
		dollar = "open"
		guillemet = "curly"
		lig-ltgteq = "flat"
		micro-sign = "tailed-serifless"
		number-sign = "slanted"
		paren = "normal"
		partial-derivative = "curly-bar"
		percent = "rings-continuous-slash"
		pilcrow = "high"
		punctuation-dot = "round"
		question = "smooth"
		tilde = "low"
		underscore = "high"

		# Other alphabets
		capital-gamma = "top-right-serifed"
		capital-lambda = "straight-top-serifed"
		eszet = "sulzbacher-descending-serifless"
		lower-alpha = "crossing"
		lower-delta = "rounded"
		lower-iota = "tailed"
		lower-lambda = "straight-turn"
		lower-mu = "tailed-serifless"
		lower-pi = "tailed"
		lower-tau = "tailed"
		lower-xi = "flat-top"

	[buildPlans.iosevka-rltb-sans.variants.italic]
		# lowercase overrides
		a = "single-storey-tailed"
		d = "tailed-serifless"
		e = "rounded"
		f = "flat-hook-tailed"
		g = "single-storey-flat-hook-serifless"
		h = "tailed-serifless"
		i = "flat-tailed"
		k = "straight-serifless"
		l = "flat-tailed"
		m = "tailed-serifless"
		n = "tailed-serifless"
		q = "tailed-serifless"
		u = "tailed-serifless"
