[buildPlans.iosevka-custom]
	family = "Iosevka RLTB"
	serifs = "sans"
	spacing = "fixed"
	# no-ligation = true

	[buildPlans.iosevka-custom.ligations]
		enables = ["kern-dotty"]

	[buildPlans.iosevka-custom.variants.design]
		# Capital letters
		capital-a = "straight-serifless"
		capital-b = "standard-serifless"
		capital-c = "serifless"
		capital-d = "more-rounded-serifless"
		capital-e = "serifless"
		capital-f = "serifless"
		capital-g = "toothed-serifless-hooked"
		capital-h = "serifless"
		capital-i = "serifed"
		capital-j = "serifed"
		capital-k = "straight-serifless"
		capital-l = "serifless"
		capital-m = "hanging"
		capital-n = "standard"
		capital-p = 'closed'
		capital-q = "crossing"
		capital-r = "curly"
		capital-s = "serifless"
		capital-t = 'serifless'
		capital-u = 'toothless-corner'
		capital-v = 'straight'
		capital-w = 'straight'
		capital-x = 'straight-serifless'
		capital-y = "straight-serifless"
		capital-z = 'straight-serifless'

		# Lowercase letters
		a = "double-storey-tailed"
		b = "toothed"
		c = 'serifless'
		d = "toothed-serifless"
		e = 'flat-crossbar'
		f = "flat-hook"
		g = "double-storey"
		h = "straight"
		i = "hooky"
		j = "serifed"
		k = "straight-serifless"
		l = "serifed-flat-tailed"
		m = "normal"
		n = "straight"
		p = "eared"
		q = "straight"
		r = "serifless"
		s = 'serifless'
		t = "flat-hook"
		u = "toothed"
		v = "straight"
		w = "straight"
		x = "straight-serifless"
		y = "straight-turn"
		z = "straight-serifless"

		# Digits
		eight = "crossing-asymmetric"
		five = "oblique-upper-left-bar"
		four = "semi-open"
		nine = "open-contour"
		one = "base"
		seven = "curly-serifless"
		six = "open-contour"
		three = "two-arcs"
		two = "curly-neck"
		zero = "unslashed-oval"

		# Puncutation
		ampersand = "closed"
		ascii-grave = "straight"
		ascii-single-quote = "straight"
		asterisk = "penta-high"
		at = "short"
		bar = "natural-slope"
		brace = "straight"
		caret = "high"
		dollar = "through"
		lig-ltgteq = "flat"
		number-sign = "slanted"
		paragraph-sign = "high"
		paren = "normal"
		percent = "rings-continuous-slash"
		punctuation-dot = "round"
		question = 'smooth'
		tilde = "low"
		underscore = "high"

		# Other alphabets
		capital-gamma = "top-right-serifed"
		cyrl-capital-ka = 'curly-serifed'
		cyrl-capital-u = 'cursive'
		cyrl-capital-ya = 'curly'
		cyrl-capital-ze = 'bilateral-serifed'
		cyrl-che = 'tailed'
		cyrl-ef = 'cursive'
		cyrl-en = 'tailed-top-left-serifed'
		cyrl-ka = 'curly-serifed'
		cyrl-ya = 'curly'
		cyrl-yeri = 'round'
		cyrl-yery = 'round-tailed'
		cyrl-ze = 'bilateral-serifed'
		eszet = "sulzbacher-tailed"
		lower-alpha = 'crossing'
		lower-delta = 'rounded'
		lower-iota = 'tailed'
		lower-lambda = "straight-turn"
		lower-mu = 'tailed'
		lower-xi = 'flat-top'
		turn-v = "straight"
