[buildPlans.iosevka-rltb-mono]
	family = "Iosevka RLTB"
	serifs = "sans"
	spacing = "term"
	webfont-formats = ["woff2", "ttf"]
	# no-ligation = true

	[buildPlans.iosevka-rltb-mono.ligations]
		enables = ["kern-dotty", "kern-bars", "center-ops"]

	[buildPlans.iosevka-rltb-mono.variants.design]
		# Capital letters
		capital-a = "straight-serifless"
		capital-b = "standard-serifless"
		capital-c = "serifless"
		capital-d = "more-rounded-serifless"
		capital-e = "serifless"
		capital-f = "serifless"
		capital-g = "toothed-serifless-hooked"
		capital-h = "serifless"
		capital-i = "serifed"
		capital-j = "serifed"
		capital-k = "straight-serifless"
		capital-l = "serifless"
		capital-m = "hanging-serifless"
		capital-n = "standard-serifless"
		capital-p = "closed-serifless"
		capital-q = "crossing-curly-tailed"
		capital-r = "straight-serifless"
		capital-s = "serifless"
		capital-t = "serifless"
		capital-u = "toothless-rounded-serifless"
		capital-v = "straight-serifless"
		capital-w = "straight-serifless"
		capital-x = "straight-serifless"
		capital-y = "straight-serifless"
		capital-z = "straight-serifless"

		# Lowercase letters
		a = "double-storey-tailed"
		b = "toothed-serifless"
		c = "serifless"
		d = "toothed-serifless"
		e = "flat-crossbar"
		f = "flat-hook-serifless"
		g = "double-storey"
		h = "straight-serifless"
		i = "serifed"
		j = "serifed"
		k = "straight-serifless"
		l = "serifed-flat-tailed"
		m = "serifless"
		n = "straight-serifless"
		p = "eared-serifless"
		q = "tailed-serifless"
		r = "serifless"
		s = "serifless"
		t = "flat-hook"
		u = "toothed-serifless"
		v = "straight-serifless"
		w = "straight-serifless"
		x = "straight-serifless"
		y = "straight-turn-serifless"
		z = "straight-serifless"

		# Digits
		eight = "crossing-asymmetric"
		five = "oblique-upper-left-bar"
		four = "closed"
		nine = "open-contour"
		one = "base"
		seven = "curly-serifless"
		six = "open-contour"
		three = "two-arcs"
		two = "curly-neck"
		zero = "oval-tall-slashed"

		# Puncutation
		ampersand = "closed"
		ascii-grave = "straight"
		ascii-single-quote = "straight"
		asterisk = "penta-high"
		at = "compact"
		bar = "natural-slope"
		brace = "curly"
		caret = "medium"
		cent = "through"
		diacritic-dot = "round"
		dollar = "through"
		lig-ltgteq = "flat"
		micro-sign = "toothed-serifless"
		number-sign = "slanted"
		paren = "normal"
		percent = "rings-continuous-slash"
		pilcrow = "high"
		punctuation-dot = "round"
		question = "smooth"
		tilde = "low"
		underscore = "high"

		# Other alphabets
		capital-gamma = "top-right-serifed"
		eszet = "sulzbacher-descending"
		long-s = "bent-hook-serifless"
		lower-alpha = "crossing"
		lower-delta = "rounded"
		lower-iota = "serifed-flat-tailed"
		lower-lambda = "straight-turn"
		lower-mu = "tailed-serifless"
		lower-xi = "flat-top"
		turn-v = "straight"

[buildPlans.iosevka-rltb-mono-alt]
	family = "Iosevka RLTB Alt"
	serifs = "sans"
	spacing = "term"
	webfont-formats = ["woff2", "ttf"]
	# no-ligation = true

	[buildPlans.iosevka-rltb-mono-alt.ligations]
		enables = ["kern-dotty", "kern-bars", "center-ops"]

	[buildPlans.iosevka-rltb-mono-alt.variants.design]
		# Capital letters
		capital-a = "straight-serifless"
		capital-b = "standard-serifless"
		capital-c = "serifless"
		capital-d = "more-rounded-serifless"
		capital-e = "serifless"
		capital-f = "serifless"
		capital-g = "toothless-rounded-serifless-hooked"
		capital-h = "serifless"
		capital-i = "serifed"
		capital-j = "serifless"
		capital-k = "straight-serifless"
		capital-l = "serifless"
		capital-m = "hanging"
		capital-n = "standard"
		capital-p = "closed"
		capital-q = "crossing"
		capital-r = "straight"
		capital-s = "serifless"
		capital-t = "serifless"
		capital-u = "toothless-rounded"
		capital-v = "straight"
		capital-w = "straight"
		capital-x = "straight-serifless"
		capital-y = "straight-serifless"
		capital-z = "straight-serifless"

		# Lowercase letters
		a = "double-storey-serifless"
		b = "toothed"
		c = "serifless"
		d = "toothed-serifless"
		e = "flat-crossbar"
		f = "flat-hook"
		g = "double-storey"
		h = "straight"
		i = "hooky"
		j = "serifed"
		k = "straight-serifless"
		l = "serifed-flat-tailed"
		m = "normal"
		n = "straight"
		p = "eared"
		q = "tailed"
		r = "compact"
		s = "serifless"
		t = "flat-hook"
		u = "toothed"
		v = "straight"
		w = "straight"
		x = "straight-serifless"
		y = "straight-turn"
		z = "straight-serifless"

		# Digits
		eight = "two-circles"
		five = "oblique-upper-left-bar"
		four = "semi-open"
		nine = "open-contour"
		one = "base"
		seven = "straight-serifless"
		six = "open-contour"
		three = "two-arcs"
		two = "curly-neck"
		zero = "dotted-oval"

		# Puncutation
		ampersand = "closed"
		ascii-grave = "straight"
		ascii-single-quote = "straight"
		asterisk = "penta-high"
		at = "short"
		bar = "natural-slope"
		brace = "straight"
		caret = "high"
		cent = "through"
		diacritic-dot = "round"
		dollar = "through"
		lig-ltgteq = "flat"
		number-sign = "slanted"
		paren = "normal"
		percent = "rings-continuous-slash"
		pilcrow = "high"
		punctuation-dot = "round"
		question = "smooth"
		tilde = "low"
		underscore = "above-baseline"


		# Other alphabets
		capital-gamma = "top-right-serifed"
		cyrl-capital-ka = "curly-serifed"
		cyrl-capital-u = "cursive"
		cyrl-capital-ya = "curly"
		cyrl-capital-ze = "bilateral-serifed"
		cyrl-che = "tailed"
		cyrl-ef = "cursive"
		cyrl-en = "tailed-top-left-serifed"
		cyrl-ka = "curly-serifed"
		cyrl-ya = "curly"
		cyrl-yeri = "round"
		cyrl-yery = "round-tailed"
		cyrl-ze = "bilateral-serifed"
		eszet = "sulzbacher-descending"
		lower-alpha = "crossing"
		lower-delta = "rounded"
		lower-iota = "tailed"
		lower-lambda = "straight-turn"
		lower-mu = "tailless"
		lower-xi = "flat-top"
		turn-v = "straight"

[buildPlans.iosevka-rltb-sans]
	export-glyph-names = false
	family = "Iosevka RLTB Sans"
	no-ligation = true
	serifs = "sans"
	spacing = "quasi-proportional"
	webfont-formats = ["woff2", "ttf"]

	[buildPlans.iosevka-rltb-sans.variants.design]
		# Capital letters
		capital-a = "straight-serifless"
		capital-b = "standard-serifless"
		capital-c = "serifless"
		capital-d = "more-rounded-serifless"
		capital-e = "serifless"
		capital-f = "serifless"
		capital-g = "toothed-serifless-hooked"
		capital-h = "serifless"
		capital-i = "serifed"
		capital-j = "serifed"
		capital-k = "straight-serifless"
		capital-l = "serifless"
		capital-m = "hanging-serifless"
		capital-n = "standard-serifless"
		capital-p = "closed-serifless"
		capital-q = "crossing"
		capital-r = "straight-serifless"
		capital-s = "serifless"
		capital-t = "serifless"
		capital-u = "toothless-rounded-serifless"
		capital-v = "straight-serifless"
		capital-w = "straight-serifless"
		capital-x = "straight-serifless"
		capital-y = "straight-serifless"
		capital-z = "straight-serifless"

		# Lowercase letters
		a = "double-storey-serifless"
		b = "toothed-serifless"
		c = "serifless"
		d = "toothed-serifless"
		e = "flat-crossbar"
		f = "flat-hook-serifless"
		g = "double-storey"
		h = "straight-serifless"
		i = "serifless"
		j = "flat-hook-serifless"
		k = "straight-serifless"
		l = "flat-tailed"
		m = "serifless"
		n = "straight-serifless"
		p = "eared-serifless"
		q = "tailed-serifless"
		r = "hookless-serifless"
		s = "serifless"
		t = "flat-hook-short-neck"
		u = "toothed-serifless"
		v = "straight-serifless"
		w = "straight-serifless"
		x = "straight-serifless"
		y = "straight-turn-serifless"
		z = "straight-serifless"

		# Digits
		eight = "crossing-asymmetric"
		five = "oblique-upper-left-bar"
		four = "semi-open"
		nine = "open-contour"
		one = "base"
		seven = "bend-serifless"
		six = "open-contour"
		three = "two-arcs"
		two = "curly-neck"
		zero = "oval-unslashed"

		# Puncutation
		ampersand = "closed"
		ascii-grave = "straight"
		ascii-single-quote = "straight"
		asterisk = "penta-high"
		at = "compact"
		bar = "natural-slope"
		brace = "straight"
		caret = "medium"
		cent = "through"
		diacritic-dot = "round"
		dollar = "open"
		guillemet = "curly"
		lig-ltgteq = "flat"
		micro-sign = "tailed-serifless"
		number-sign = "slanted"
		paren = "normal"
		partial-derivative = "curly-bar"
		percent = "rings-continuous-slash"
		pilcrow = "high"
		punctuation-dot = "round"
		question = "smooth"
		tilde = "low"
		underscore = "high"

		# Other alphabets
		capital-gamma = "top-right-serifed"
		capital-lambda = "straight-top-serifed"
		eszet = "sulzbacher-descending-serifless"
		lower-alpha = "crossing"
		lower-delta = "rounded"
		lower-iota = "tailed"
		lower-lambda = "straight-turn"
		lower-mu = "tailed-serifless"
		lower-pi = "tailed"
		lower-tau = "tailed"
		lower-xi = "flat-top"

	[buildPlans.iosevka-rltb-sans.variants.italic]
		# lowercase overrides
		a = "single-storey-serifed"
		d = "tailed-serifless"
		e = "rounded"
		f = "flat-hook-tailed"
		g = "single-storey-flat-hook-serifless"
		h = "tailed-serifless"
		i = "flat-tailed"
		k = "straight-serifless"
		l = "flat-tailed"
		m = "tailed-serifless"
		n = "tailed-serifless"
		q = "tailed-serifless"
		u = "toothed-bottom-right-serifed"
		v = "straight-serifless"
		w = "straight-serifless"
		y = "straight-turn-serifless"
